name: Test Pull Request
on:
  pull_request:

jobs:
  test:
    runs-on: [self-hosted, linux]
    steps:
    - name: Checking out repository
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Run Tests
      run: dotnet test Nitrox.Test/Nitrox.Test.csproj --logger trx --results-directory "test_results"

    - name: Upload Event File
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      with:
        name: Event File
        path: ${{ github.event_path }}

    - name: Upload Test Results
      uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
      if: (!cancelled())
      with:
        name: Test Results
        path: |
          test_results/*.trx
